In [1]:
  import numpy as np

In [4]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
np.random.shuffle(a)
a

array([11,  5,  0, 10,  3,  9,  7,  1, 15,  6, 13,  2, 12, 14,  4,  8])

In [16]:
batch_size = 4
b = np.random.choice(a, batch_size, replace=False)
b

array([ 4,  1,  5, 11])

In [21]:
a = np.arange(16)
np.random.shuffle(a)
b = np.random.choice(a, batch_size, replace=False)
b

array([10, 14,  6,  7])